reserva/urls.py
from django.urls import path

from reserva.views import reserva

app_name = 'reserva'

urlpatterns = [
  path('criar/', reserva, name='criar_reserva'),
]

ultima/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from base.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio),
    path('contato/', contato),
    path('reserva-antigo/', reserva),
    path('reserva/', include('reserva.urls', namespace='reserva')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('rest_api.urls', namespace='rest_api'))
]

base/models.py
from django.db import models

# Create your models here.
class Contato(models.Model):
    nome = models.CharField(max_length=50)
    email = models.EmailField()
    mensagem = models.TextField()
    data = models.DateTimeField(auto_now_add=True)
    lido = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return f'{self.nome}: [{self.email}]'
    class Meta:
        verbose_name = 'Formulário de Contato'
        verbose_name_plural = 'Formulários de Contatos'
        ordering = ['-data']


class Reserva(models.Model):
    nomeDoPet = models.CharField(max_length=50)
    telefone = models.CharField(max_length=15)
    dia = models.DateField()
    observacoes = models.TextField()
    data = models.DateTimeField(auto_now_add=True)

reserva/models.py
from django.db import models

# Create your models here.
class Reserva(models.Model):
  OPCOES_DE_TURNO = (
    ('manha', 'Manhã'),
    ('tarde', 'Tarde')
  )
  OPCOES_DE_TAMANHO = (
    (0, 'Pequeno'),
    (1, 'Médio'),
    (2, 'Grande')
  )
  nomeDoPet = models.CharField(max_length=50, verbose_name='Nome do PET')
  telefone = models.CharField(max_length=15, verbose_name='Telefone')
  observacoes = models.TextField(blank=True, verbose_name='Observações')
  data = models.DateField(verbose_name='Data')
  turno = models.CharField(max_length=5, choices=OPCOES_DE_TURNO, verbose_name='Turno')
  tamanho = models.IntegerField(choices=OPCOES_DE_TAMANHO, verbose_name='Tamanho')
  petshop = models.ForeignKey(
    'Petshop',
    verbose_name='petshops',
    related_name='reservas',
    on_delete=models.CASCADE,
    blank=True,
    null=True
  )
  categoria_animal = models.ForeignKey(
    'CategoriaAnimal',
    verbose_name='Categoria do Animal',
    on_delete=models.CASCADE,
    related_name='reservas',
    blank=True,
)

  def __str__(self):
    return f'{self.nomeDoPet} - {self.data} - {self.turno}'
  
  class Meta:
    verbose_name = 'Reserva de Banho'
    verbose_name_plural = 'Reservas de Banho'
    ordering = ['-data']


class Petshop(models.Model):
  nome = models.CharField(verbose_name="Nome do petshop", max_length=50)
  endereco = models.CharField(verbose_name="Endereço", max_length=150)
  numero = models.CharField(verbose_name="Número", max_length=10)
  bairro = models.CharField(verbose_name="Bairro", max_length=30)
  
class CategoriaAnimal(models.Model):
    nome_categoria = models.CharField(max_length=50, verbose_name='Nome da Categoria')

    def __str__(self):
        return self.nome_categoria

base/forms.py
from django import forms
from base.models import Contato
from base.models import Reserva

class ContatoForm(forms.ModelForm):
  class Meta:
    model = Contato
    fields = ['nome', 'email', 'mensagem']

class ReservaForm(forms.ModelForm):
  class Meta:
    model = Reserva
    fields = ['nomeDoPet', 'telefone', 'dia', 'observacoes']
    labels = {
      'nomeDoPet': 'Nome do PET',
      'dia': 'Dia da Reserva'
    }
    widgets = {
      'dia': forms.DateInput(attrs={ 'type': 'date'})
    }

reserva/forms.py
from django import forms
from datetime import date

from reserva.models import Reserva

class ReservaForm(forms.ModelForm):

  def clean_data(self):
    data = self.cleaned_data['data']
    hoje = date.today()

    if data < hoje:
      raise forms.ValidationError('Não é possível reservar um banho para uma data no passado')

    quantidadeDeReservasParaODiaEscolhido = Reserva.objects.filter(data=data).count()

    if quantidadeDeReservasParaODiaEscolhido >= 4:
      raise forms.ValidationError('O limite máximo de reservas para este dia já foi alcançado')

    return data

  class Meta:
    fields = ['nomeDoPet', 'telefone', 'data', 'turno', 'tamanho', 'observacoes']
    model = Reserva
    widgets = {
      'data': forms.DateInput(attrs={ 'type': 'date'})
    }

base/views.py
from django.shortcuts import render
from base.forms import ContatoForm
from base.forms import ReservaForm

# Create your views here.
def inicio(request):
  return render(request, 'inicio.html')


def contato(request):
  sucesso = False

  form = ContatoForm(request.POST or None)
  print(form.as_p())
  if (form.is_valid()):
    form.save()
    sucesso = True
  
  context = {
    'telefone': '81 99999999',
    'nome': 'Fabio Mariano',
    'formulario': form,
    'sucesso': sucesso
  }

  return render(request, 'contato.html', context)


def reserva(request):
  sucesso = False

  form = ReservaForm(request.POST or None)

  if (form.is_valid()):
    form.save()
    sucesso = True
  
  context = {
    'formulario': form,
    'sucesso': sucesso
  }
  return render(request, 'reserva.html', context)

reserva/views.py
from django.shortcuts import render

from reserva.forms import ReservaForm

# Create your views here.
def reserva(request):
  sucesso = False

  form = ReservaForm(request.POST or None)

  if (form.is_valid()):
    form.save()
    sucesso = True
  
  context = {
    'formulario': form,
    'sucesso': sucesso
  }
  return render(request, 'reserva_de_banho.html', context)

base/templates/contato.html
<main>
  {% extends "inicio.html" %}
  {% block principal %}
  <div class="container">
    <h1 class="text-center">Fale Conosco</h1>
    <p>
      Envie uma mensagem através do formulário abaixo ou ligue para o telefone {{ telefone }} falando com o responsável {{ responsavel|upper }}
    </p>
    {%if sucesso %}
      <p class="alert alert-success">Mensagem enviada com sucesso!</p>
    {% else %}
      <form action="" method="post" novalidate>
        {% load bootstrap5 %}
        {% csrf_token %}
        {% bootstrap_form formulario %}
        <hr>
        <button type="submit" class="btn btn-primary">Enviar Mensagem</button>
      </form>
    {% endif %}
  </div>
  {% endblock %}
</main>

base/templates/inicio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Aula de Hoje - Última</title>
    
    <!--Template based on URL below-->
    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <main role="main">
    <div class="p-5 bg-primary text-white text-center">
      <h1>Petshop</h1>
    </div>
    {% block principal %}
      <p>Sobre minha empresa...</p>
      <a href="{% url 'reserva:criar_reserva' %}">Reserve um banho agora!</a>
    {% endblock %}
  </main>

</body>
</html>

base/templates/reserva.html
<main>
  {% extends "inicio.html" %}
  {% block principal %}
  <div class="container">
    <h1 class="text-center">
      Faça uma reserva agora!
    </h1>
    {%if sucesso %}
      <p class="alert alert-success">Mensagem enviada com sucesso!</p>
    {% else %}
      <form action="" method="post" novalidate>
        {% load bootstrap5 %}
        {% csrf_token %}
        {% bootstrap_form formulario %}
        <hr>
        <button type="submit" class="btn btn-primary">Enviar Mensagem</button>
      </form>
    {% endif %}
  </div>
  {% endblock %}
</main>